alias c=clear
alias gi="git init"
alias gs="git status"
alias gm="git commit -m"
alias gpu="git push"
alias gpuf="git push -f"
alias ups="git push -u origin"
alias gl="git log"
alias gcb="git checkout -b"
alias gb="git branch"
alias gc="git checkout"
alias gri="git rebase -i"
alias grm="git rebase master"
alias gcm="git checkout master"
alias ga="git add"
alias gaa="git add ."
alias gp="git pull"
export PATH="~/bin"
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
alias sublime=subl
alias python=/usr/local/bin/python3
alias pip=/usr/local/bin/pip3
